<?php

declare(strict_types=1);

namespace App\Core;

final class Schema
{
    public const VERSION = '2026_09_25_001';

    public static function install(): void
    {
        $pdo = Database::pdo();
        $installed = false;
        try {
            $installed = (bool) $pdo->query("SELECT 1 FROM schema_migrations WHERE version = '" . self::VERSION . "'")->fetchColumn();
        } catch (\PDOException) {
            $installed = false;
        }
        if ($installed) {
            return;
        }

        foreach (self::statements(Database::driver()) as $sql) {
            $pdo->exec($sql);
        }
        $pdo->exec("INSERT INTO schema_migrations (version, applied_at) VALUES ('" . self::VERSION . "', '" . date('Y-m-d H:i:s') . "')");
    }

    /** @return array<int, string> */
    public static function statements(string $driver): array
    {
        $map = $driver === 'pgsql'
            ? [
                '{pk}' => 'BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY',
                '{fk}' => 'BIGINT',
                '{ts}' => 'TIMESTAMP(0)',
                '{date}' => 'DATE',
                '{time}' => 'TIME(0)',
                '{bool}' => 'SMALLINT',
                '{money}' => 'BIGINT',
                '{real}' => 'REAL',
                '{bigint}' => 'BIGINT',
            ]
            : [
                '{pk}' => 'INTEGER PRIMARY KEY AUTOINCREMENT',
                '{fk}' => 'INTEGER',
                '{ts}' => 'TEXT',
                '{date}' => 'TEXT',
                '{time}' => 'TEXT',
                '{bool}' => 'INTEGER',
                '{money}' => 'INTEGER',
                '{real}' => 'REAL',
                '{bigint}' => 'INTEGER',
            ];

        return array_map(static fn (string $sql): string => strtr($sql, $map), self::ddl());
    }

    /** @return array<int, string> */
    private static function ddl(): array
    {
        return [
            'CREATE TABLE IF NOT EXISTS schema_migrations (
                version TEXT PRIMARY KEY,
                applied_at {ts} NOT NULL
            )',
            "CREATE TABLE IF NOT EXISTS users (
                id {pk},
                uuid TEXT NOT NULL UNIQUE,
                email TEXT NOT NULL UNIQUE,
                password_hash TEXT NOT NULL,
                role TEXT NOT NULL CHECK (role IN ('admin', 'creator', 'company')),
                admin_level TEXT CHECK (admin_level IS NULL OR admin_level IN ('master', 'staff')),
                status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'blocked')),
                blocked_reason TEXT,
                email_verified_at {ts},
                last_login_at {ts},
                last_login_ip TEXT,
                last_seen_at {ts},
                created_at {ts} NOT NULL,
                updated_at {ts} NOT NULL,
                deleted_at {ts}
            )",
            'CREATE TABLE IF NOT EXISTS profiles (
                id {pk},
                user_id {fk} NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
                display_name TEXT NOT NULL,
                slug TEXT NOT NULL UNIQUE,
                avatar_path TEXT,
                phone TEXT,
                city TEXT,
                state TEXT,
                headline TEXT,
                bio TEXT,
                experience_years INTEGER,
                specialties TEXT,
                professional_info TEXT,
                created_at {ts} NOT NULL,
                updated_at {ts} NOT NULL
            )',
            'CREATE TABLE IF NOT EXISTS creators (
                id {pk},
                user_id {fk} NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
                is_verified {bool} NOT NULL DEFAULT 0,
                verified_at {ts},
                verification_requested_at {ts},
                min_notice_hours INTEGER NOT NULL DEFAULT 48,
                unavailable_from {date},
                unavailable_until {date},
                unavailable_note TEXT,
                rating_avg {real} NOT NULL DEFAULT 0,
                rating_count INTEGER NOT NULL DEFAULT 0,
                contracts_count INTEGER NOT NULL DEFAULT 0,
                hours_sold INTEGER NOT NULL DEFAULT 0,
                created_at {ts} NOT NULL,
                updated_at {ts} NOT NULL
            )',
            'CREATE TABLE IF NOT EXISTS companies (
                id {pk},
                user_id {fk} NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
                company_name TEXT NOT NULL,
                legal_name TEXT,
                document TEXT,
                responsible_name TEXT NOT NULL,
                phone TEXT,
                city TEXT,
                state TEXT,
                website TEXT,
                created_at {ts} NOT NULL,
                updated_at {ts} NOT NULL
            )',
            "CREATE TABLE IF NOT EXISTS categories (
                id {pk},
                name TEXT NOT NULL,
                slug TEXT NOT NULL UNIQUE,
                description TEXT,
                image_path TEXT,
                status TEXT NOT NULL DEFAULT 'visible' CHECK (status IN ('visible', 'hidden')),
                sort_order INTEGER NOT NULL DEFAULT 0,
                created_at {ts} NOT NULL,
                updated_at {ts} NOT NULL
            )",
            "CREATE TABLE IF NOT EXISTS listings (
                id {pk},
                uuid TEXT NOT NULL UNIQUE,
                creator_id {fk} NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                category_id {fk} REFERENCES categories(id) ON DELETE SET NULL,
                title TEXT NOT NULL DEFAULT '',
                slug TEXT NOT NULL UNIQUE,
                short_description TEXT NOT NULL DEFAULT '',
                description TEXT NOT NULL DEFAULT '',
                what_company_buys TEXT,
                what_company_provides TEXT,
                how_it_works TEXT,
                framing TEXT,
                additional_info TEXT,
                video_url TEXT,
                cover_path TEXT,
                status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'pending', 'active', 'paused', 'rejected')),
                rejection_reason TEXT,
                wizard_step INTEGER NOT NULL DEFAULT 1,
                starting_price_cents {money} NOT NULL DEFAULT 0,
                min_delivery_days INTEGER NOT NULL DEFAULT 0,
                views_count INTEGER NOT NULL DEFAULT 0,
                contacts_count INTEGER NOT NULL DEFAULT 0,
                contracts_count INTEGER NOT NULL DEFAULT 0,
                rating_avg {real} NOT NULL DEFAULT 0,
                rating_count INTEGER NOT NULL DEFAULT 0,
                submitted_at {ts},
                approved_at {ts},
                published_at {ts},
                created_at {ts} NOT NULL,
                updated_at {ts} NOT NULL,
                deleted_at {ts}
            )",
            'CREATE TABLE IF NOT EXISTS listing_packages (
                id {pk},
                listing_id {fk} NOT NULL REFERENCES listings(id) ON DELETE CASCADE,
                hours INTEGER NOT NULL CHECK (hours BETWEEN 1 AND 24),
                price_cents {money} NOT NULL CHECK (price_cents >= 0),
                delivery_days INTEGER NOT NULL CHECK (delivery_days >= 1),
                revisions INTEGER NOT NULL DEFAULT 0 CHECK (revisions >= 0),
                description TEXT,
                sort_order INTEGER NOT NULL DEFAULT 0,
                created_at {ts} NOT NULL,
                updated_at {ts} NOT NULL
            )',
            'CREATE TABLE IF NOT EXISTS listing_addons (
                id {pk},
                listing_id {fk} NOT NULL REFERENCES listings(id) ON DELETE CASCADE,
                name TEXT NOT NULL,
                description TEXT,
                price_cents {money} NOT NULL CHECK (price_cents >= 0),
                extra_days INTEGER NOT NULL DEFAULT 0 CHECK (extra_days >= 0),
                sort_order INTEGER NOT NULL DEFAULT 0,
                created_at {ts} NOT NULL,
                updated_at {ts} NOT NULL
            )',
            'CREATE TABLE IF NOT EXISTS listing_images (
                id {pk},
                listing_id {fk} NOT NULL REFERENCES listings(id) ON DELETE CASCADE,
                path TEXT NOT NULL,
                thumb_path TEXT,
                alt_text TEXT,
                is_primary {bool} NOT NULL DEFAULT 0,
                sort_order INTEGER NOT NULL DEFAULT 0,
                created_at {ts} NOT NULL
            )',
            'CREATE TABLE IF NOT EXISTS listing_faqs (
                id {pk},
                listing_id {fk} NOT NULL REFERENCES listings(id) ON DELETE CASCADE,
                question TEXT NOT NULL,
                answer TEXT NOT NULL,
                sort_order INTEGER NOT NULL DEFAULT 0,
                created_at {ts} NOT NULL,
                updated_at {ts} NOT NULL
            )',
            "CREATE TABLE IF NOT EXISTS listing_moderations (
                id {pk},
                listing_id {fk} NOT NULL REFERENCES listings(id) ON DELETE CASCADE,
                actor_id {fk} REFERENCES users(id) ON DELETE SET NULL,
                action TEXT NOT NULL CHECK (action IN ('submitted', 'approved', 'rejected', 'paused', 'reactivated', 'deleted')),
                reason TEXT,
                created_at {ts} NOT NULL
            )",
            'CREATE TABLE IF NOT EXISTS availability (
                id {pk},
                creator_id {fk} NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                weekday INTEGER NOT NULL CHECK (weekday BETWEEN 0 AND 6),
                start_time {time} NOT NULL,
                end_time {time} NOT NULL,
                created_at {ts} NOT NULL,
                updated_at {ts} NOT NULL,
                UNIQUE (creator_id, weekday)
            )',
            'CREATE TABLE IF NOT EXISTS conversations (
                id {pk},
                uuid TEXT NOT NULL UNIQUE,
                company_id {fk} NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                creator_id {fk} NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                listing_id {fk} REFERENCES listings(id) ON DELETE SET NULL,
                last_message_at {ts},
                company_read_at {ts},
                creator_read_at {ts},
                created_at {ts} NOT NULL,
                updated_at {ts} NOT NULL,
                UNIQUE (company_id, creator_id, listing_id)
            )',
            'CREATE TABLE IF NOT EXISTS messages (
                id {pk},
                conversation_id {fk} NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
                sender_id {fk} NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                body TEXT NOT NULL,
                created_at {ts} NOT NULL
            )',
            "CREATE TABLE IF NOT EXISTS requests (
                id {pk},
                uuid TEXT NOT NULL UNIQUE,
                code TEXT NOT NULL UNIQUE,
                company_id {fk} NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                creator_id {fk} NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                listing_id {fk} NOT NULL REFERENCES listings(id) ON DELETE CASCADE,
                package_id {fk} REFERENCES listing_packages(id) ON DELETE SET NULL,
                conversation_id {fk} REFERENCES conversations(id) ON DELETE SET NULL,
                hours INTEGER NOT NULL,
                package_price_cents {money} NOT NULL,
                addons_cents {money} NOT NULL DEFAULT 0,
                total_cents {money} NOT NULL,
                addons_json TEXT,
                desired_date {date},
                desired_time {time},
                theme TEXT NOT NULL,
                briefing TEXT,
                message TEXT,
                status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'accepted', 'declined', 'expired', 'cancelled')),
                decline_reason TEXT,
                expires_at {ts},
                responded_at {ts},
                created_at {ts} NOT NULL,
                updated_at {ts} NOT NULL
            )",
            "CREATE TABLE IF NOT EXISTS contracts (
                id {pk},
                uuid TEXT NOT NULL UNIQUE,
                code TEXT NOT NULL UNIQUE,
                request_id {fk} NOT NULL UNIQUE REFERENCES requests(id) ON DELETE CASCADE,
                company_id {fk} NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                creator_id {fk} NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                listing_id {fk} NOT NULL REFERENCES listings(id) ON DELETE CASCADE,
                package_id {fk} REFERENCES listing_packages(id) ON DELETE SET NULL,
                conversation_id {fk} REFERENCES conversations(id) ON DELETE SET NULL,
                hours INTEGER NOT NULL,
                package_price_cents {money} NOT NULL,
                addons_cents {money} NOT NULL DEFAULT 0,
                total_cents {money} NOT NULL,
                fee_cents {money} NOT NULL DEFAULT 0,
                creator_amount_cents {money} NOT NULL,
                addons_json TEXT,
                scheduled_date {date},
                scheduled_time {time},
                theme TEXT NOT NULL,
                briefing TEXT,
                status TEXT NOT NULL DEFAULT 'awaiting_payment' CHECK (status IN ('awaiting_payment', 'confirmed', 'in_progress', 'completed', 'cancelled')),
                paid_at {ts},
                confirmed_at {ts},
                started_at {ts},
                completed_at {ts},
                cancelled_at {ts},
                cancel_reason TEXT,
                created_at {ts} NOT NULL,
                updated_at {ts} NOT NULL
            )",
            'CREATE TABLE IF NOT EXISTS contract_events (
                id {pk},
                contract_id {fk} NOT NULL REFERENCES contracts(id) ON DELETE CASCADE,
                actor_id {fk} REFERENCES users(id) ON DELETE SET NULL,
                type TEXT NOT NULL,
                note TEXT,
                created_at {ts} NOT NULL
            )',
            "CREATE TABLE IF NOT EXISTS attachments (
                id {pk},
                uuid TEXT NOT NULL UNIQUE,
                owner_id {fk} NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                context TEXT NOT NULL CHECK (context IN ('request', 'contract', 'message')),
                context_id {fk} NOT NULL,
                disk TEXT NOT NULL DEFAULT 'private',
                path TEXT NOT NULL,
                original_name TEXT NOT NULL,
                mime TEXT NOT NULL,
                size_bytes {bigint} NOT NULL,
                created_at {ts} NOT NULL
            )",
            "CREATE TABLE IF NOT EXISTS payments (
                id {pk},
                uuid TEXT NOT NULL UNIQUE,
                contract_id {fk} NOT NULL REFERENCES contracts(id) ON DELETE CASCADE,
                company_id {fk} NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                creator_id {fk} NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                amount_cents {money} NOT NULL,
                fee_cents {money} NOT NULL DEFAULT 0,
                net_cents {money} NOT NULL,
                status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'paid', 'awaiting_payout', 'paid_out', 'cancelled', 'refunded')),
                method TEXT,
                gateway TEXT,
                gateway_reference TEXT,
                gateway_payload TEXT,
                paid_at {ts},
                paid_out_at {ts},
                cancelled_at {ts},
                refunded_at {ts},
                created_at {ts} NOT NULL,
                updated_at {ts} NOT NULL
            )",
            "CREATE TABLE IF NOT EXISTS reviews (
                id {pk},
                contract_id {fk} NOT NULL UNIQUE REFERENCES contracts(id) ON DELETE CASCADE,
                listing_id {fk} NOT NULL REFERENCES listings(id) ON DELETE CASCADE,
                creator_id {fk} NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                company_id {fk} NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                rating INTEGER NOT NULL CHECK (rating BETWEEN 1 AND 5),
                comment TEXT NOT NULL,
                status TEXT NOT NULL DEFAULT 'visible' CHECK (status IN ('visible', 'hidden')),
                moderated_by {fk} REFERENCES users(id) ON DELETE SET NULL,
                moderated_at {ts},
                moderation_note TEXT,
                created_at {ts} NOT NULL,
                updated_at {ts} NOT NULL
            )",
            'CREATE TABLE IF NOT EXISTS notifications (
                id {pk},
                user_id {fk} NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                type TEXT NOT NULL,
                title TEXT NOT NULL,
                body TEXT,
                url TEXT,
                read_at {ts},
                created_at {ts} NOT NULL
            )',
            "CREATE TABLE IF NOT EXISTS reports (
                id {pk},
                uuid TEXT NOT NULL UNIQUE,
                reporter_id {fk} REFERENCES users(id) ON DELETE SET NULL,
                target_type TEXT NOT NULL CHECK (target_type IN ('listing', 'creator', 'company', 'contract', 'message')),
                target_id {fk} NOT NULL,
                reason TEXT NOT NULL,
                description TEXT,
                status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'reviewing', 'resolved', 'archived')),
                response TEXT,
                resolved_by {fk} REFERENCES users(id) ON DELETE SET NULL,
                resolved_at {ts},
                created_at {ts} NOT NULL,
                updated_at {ts} NOT NULL
            )",
            'CREATE TABLE IF NOT EXISTS report_notes (
                id {pk},
                report_id {fk} NOT NULL REFERENCES reports(id) ON DELETE CASCADE,
                admin_id {fk} REFERENCES users(id) ON DELETE SET NULL,
                note TEXT NOT NULL,
                created_at {ts} NOT NULL
            )',
            "CREATE TABLE IF NOT EXISTS favorites (
                id {pk},
                user_id {fk} NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                target_type TEXT NOT NULL CHECK (target_type IN ('listing', 'creator')),
                target_id {fk} NOT NULL,
                created_at {ts} NOT NULL,
                UNIQUE (user_id, target_type, target_id)
            )",
            'CREATE TABLE IF NOT EXISTS admin_actions (
                id {pk},
                admin_id {fk} REFERENCES users(id) ON DELETE SET NULL,
                action TEXT NOT NULL,
                object_type TEXT NOT NULL,
                object_id {fk},
                description TEXT NOT NULL,
                ip TEXT,
                meta TEXT,
                created_at {ts} NOT NULL
            )',
            'CREATE TABLE IF NOT EXISTS activity_log (
                id {pk},
                user_id {fk} REFERENCES users(id) ON DELETE SET NULL,
                action TEXT NOT NULL,
                object_type TEXT,
                object_id {fk},
                description TEXT NOT NULL,
                ip TEXT,
                created_at {ts} NOT NULL
            )',
            "CREATE TABLE IF NOT EXISTS settings (
                setting_key TEXT PRIMARY KEY,
                setting_value TEXT,
                setting_group TEXT NOT NULL DEFAULT 'general',
                updated_at {ts} NOT NULL
            )",
            "CREATE TABLE IF NOT EXISTS faqs (
                id {pk},
                question TEXT NOT NULL,
                answer TEXT NOT NULL,
                audience TEXT NOT NULL DEFAULT 'all' CHECK (audience IN ('all', 'company', 'creator')),
                status TEXT NOT NULL DEFAULT 'visible' CHECK (status IN ('visible', 'hidden')),
                sort_order INTEGER NOT NULL DEFAULT 0,
                created_at {ts} NOT NULL,
                updated_at {ts} NOT NULL
            )",
            "CREATE TABLE IF NOT EXISTS pages (
                id {pk},
                slug TEXT NOT NULL UNIQUE,
                title TEXT NOT NULL,
                content TEXT NOT NULL,
                status TEXT NOT NULL DEFAULT 'published' CHECK (status IN ('published', 'draft')),
                created_at {ts} NOT NULL,
                updated_at {ts} NOT NULL
            )",
            "CREATE TABLE IF NOT EXISTS home_highlights (
                id {pk},
                section TEXT NOT NULL CHECK (section IN ('featured_creators', 'most_hired', 'new_listings', 'video_for_company', 'video_types')),
                item_type TEXT NOT NULL CHECK (item_type IN ('creator', 'listing', 'category')),
                item_id {fk} NOT NULL,
                sort_order INTEGER NOT NULL DEFAULT 0,
                created_at {ts} NOT NULL,
                UNIQUE (section, item_type, item_id)
            )",
            'CREATE TABLE IF NOT EXISTS security_tokens (
                id {pk},
                user_id {fk} NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                token_hash TEXT NOT NULL UNIQUE,
                type TEXT NOT NULL,
                expires_at {ts} NOT NULL,
                used_at {ts},
                created_at {ts} NOT NULL
            )',
            'CREATE TABLE IF NOT EXISTS sessions (
                id TEXT PRIMARY KEY,
                user_id {fk},
                payload TEXT NOT NULL,
                last_activity {bigint} NOT NULL
            )',
            'CREATE TABLE IF NOT EXISTS rate_limits (
                rate_key TEXT PRIMARY KEY,
                hits INTEGER NOT NULL,
                window_start {bigint} NOT NULL
            )',

            'CREATE INDEX IF NOT EXISTS idx_users_role ON users (role, status, created_at)',
            'CREATE INDEX IF NOT EXISTS idx_listings_public ON listings (status, published_at)',
            'CREATE INDEX IF NOT EXISTS idx_listings_creator ON listings (creator_id, status)',
            'CREATE INDEX IF NOT EXISTS idx_listings_category ON listings (category_id, status)',
            'CREATE INDEX IF NOT EXISTS idx_listing_packages ON listing_packages (listing_id, sort_order)',
            'CREATE INDEX IF NOT EXISTS idx_listing_addons ON listing_addons (listing_id, sort_order)',
            'CREATE INDEX IF NOT EXISTS idx_listing_images ON listing_images (listing_id, sort_order)',
            'CREATE INDEX IF NOT EXISTS idx_listing_faqs ON listing_faqs (listing_id, sort_order)',
            'CREATE INDEX IF NOT EXISTS idx_listing_moderations ON listing_moderations (listing_id, created_at)',
            'CREATE INDEX IF NOT EXISTS idx_requests_creator ON requests (creator_id, status, created_at)',
            'CREATE INDEX IF NOT EXISTS idx_requests_company ON requests (company_id, status, created_at)',
            'CREATE INDEX IF NOT EXISTS idx_requests_status ON requests (status, created_at)',
            'CREATE INDEX IF NOT EXISTS idx_contracts_creator ON contracts (creator_id, status, scheduled_date)',
            'CREATE INDEX IF NOT EXISTS idx_contracts_company ON contracts (company_id, status, created_at)',
            'CREATE INDEX IF NOT EXISTS idx_contracts_status ON contracts (status, created_at)',
            'CREATE INDEX IF NOT EXISTS idx_contract_events ON contract_events (contract_id, created_at)',
            'CREATE INDEX IF NOT EXISTS idx_conversations_company ON conversations (company_id, last_message_at)',
            'CREATE INDEX IF NOT EXISTS idx_conversations_creator ON conversations (creator_id, last_message_at)',
            'CREATE INDEX IF NOT EXISTS idx_messages_conversation ON messages (conversation_id, created_at)',
            'CREATE INDEX IF NOT EXISTS idx_attachments_context ON attachments (context, context_id)',
            'CREATE INDEX IF NOT EXISTS idx_payments_status ON payments (status, created_at)',
            'CREATE INDEX IF NOT EXISTS idx_payments_creator ON payments (creator_id, status)',
            'CREATE INDEX IF NOT EXISTS idx_payments_contract ON payments (contract_id)',
            'CREATE INDEX IF NOT EXISTS idx_reviews_listing ON reviews (listing_id, status, created_at)',
            'CREATE INDEX IF NOT EXISTS idx_reviews_creator ON reviews (creator_id, status)',
            'CREATE INDEX IF NOT EXISTS idx_notifications_user ON notifications (user_id, read_at, created_at)',
            'CREATE INDEX IF NOT EXISTS idx_reports_status ON reports (status, created_at)',
            'CREATE INDEX IF NOT EXISTS idx_favorites_target ON favorites (target_type, target_id)',
            'CREATE INDEX IF NOT EXISTS idx_admin_actions_created ON admin_actions (created_at)',
            'CREATE INDEX IF NOT EXISTS idx_activity_created ON activity_log (created_at)',
            'CREATE INDEX IF NOT EXISTS idx_activity_user ON activity_log (user_id, created_at)',
            'CREATE INDEX IF NOT EXISTS idx_sessions_activity ON sessions (last_activity)',
            'CREATE INDEX IF NOT EXISTS idx_home_highlights ON home_highlights (section, sort_order)',
        ];
    }
}
